### ISSUE TITLE
Support for NI_XZ drive

### ISSUE THREAD

**Issue by pheuer** [BaPSF/bapsflib#20]
The package doesn't currently seem to support the NI_XZ drive: can we get that added as another controller option?

**Comment by rocco8773** [comment]
Yes, the `NI_XZ` control device is currently not among the mappable devices.  It is schedule to be added to the package for version v1.0.1.

I'll put some effort into in the coming weeks so it should become available on the development branch sooner.

**Comment by rocco8773** [comment]
I just added functionality for the 'NI_XZ' control device to the master branch.  This will be included in the v1.0.1 release, but for now you can install a copy from the master branch. (see [installation instructions](https://bapsflib.readthedocs.io/en/latest/installation.html))

I'm going to close the issue, but keep the conversation open for now.  Let me know if anything comes up.
