### ISSUE TITLE
Converting magnetic field MSI coordinates to z or port number

### ISSUE THREAD

**Issue by physicistphil** [BaPSF/bapsflib#21]
It'd be super nice to be able to convert from the arbitrary magnetic field MSI coordinates (which range from 0-1023), found in `f.read_msi(msi_diag='magnetic field')['magnetic field'][0]` where `f` is an `bapsflib.lapd._hdf.files.File`. 

I suppose this could be done in several ways. One of which is to add a `['z']` field to the magnetic field part of the `HFReadMSI` class (like what's done with `['signal']` and `['meta']`). Allowing for this special case would probably be a bit of a mess for virtually no reward unless the magnetic field MSI coordinates are to change at some point in the future. 

It appears the z coordinates are the same for every HDF5 file, so it may be a better idea to add the whole array (or the z spacing = 2.271 cm) as a constant into the `lapd.constants` module if the `astropy.constants.Constant` allows arrays (I haven't dug any deeper on this). Perhaps a function to return the magnetic field at a specific port would be the best way to go about this.

Thoughts?
-Phil

**Comment by physicistphil** [comment]
> If you look to `data.info['z']` then you'll see the `z` array associated with the magnetic field.
> 
> Does this address your issue?

Ah, yeah. Looks like my bapsflib installation was outdated (wasn't seeing it in the dtype). 

Do you think adding a conversion function would be useful? Not sure how many people would actually need this.

**Comment by rocco8773** [comment]
You should be able to convert the z-array (`data.info['z']`) to port numbers using `bapsflib.lapd.tools.z_to_portnum`.

i.e. `pn = bapsflib.lapd.tools.z_to_portnum(data.info['z'])`

**Comment by physicistphil** [comment]
Does the trick. Thanks!

**Comment by rocco8773** [comment]
Cool!  I'm going to close the issue, but comment if anything else pops up.
