### ISSUE TITLE
Make nshots and nti variables accessible without loading data

### ISSUE THREAD

**Issue by pheuer** [BaPSF/bapsflib#24]
It would be helpful if the total number of shots (eg. the maximum of the Shot number column in the run sequence) was an easily accessible variable before any data was read in. Maybe this could be an attribute returned in the .info dictionary? 

It would be similarly helpful if the number of time indices (nti) were easily accessible for a given digitizer. 

Knowing both of these variables upfront  would be helpful for initializing an output hdf file and then reading data in chunks.

**Comment by pheuer** [comment]
(It's possible both of these are already possible, but I couldn't figure it out from the documentation)

**Comment by rocco8773** [comment]
This does already exist for digitizers, but not for controls or the msi.  The easiest way to get to this is through the `construct_dataset_name` method. For example,

```
>>> form bapsflib import lapd
>>> f = lapd.File('test.hdf5)
>>>
>>> # grab digi map
>>> digi = f.digitizer['SIS crate']
>>>
>>> # grab info for the desired dataset (brd=1, ch=2)
>>> # * this info dict is used to see the info attr when using f.read_data()
>>> name, info = digi.construct_dataset_name(1, 2, config_name='config01', adc='SIS 3302', return_info=True)
>>>
>>> info['nshotnum']  # number of shot numbers in dataset
100
>>> info['nt']  # number of time samples in dataset
1000


```

see [`construct_dataset_name` signature](https://bapsflib.readthedocs.io/en/latest/src/bapsflib._hdf.maps.digitizers.siscrate.html#bapsflib._hdf.maps.digitizers.siscrate.HDFMapDigiSISCrate.construct_dataset_name)

**Comment by pheuer** [comment]
This works! Thanks! 

(small typo above: should be f.digitizers, with an s?)

**Comment by rocco8773** [comment]
Awesome! I updated the comment to reflect `f.digitizers`
