### ISSUE TITLE
Error shotnum or index keyword AND add_controls for read_data()

### ISSUE THREAD

**Issue by pheuer** [BaPSF/bapsflib#25]
Currently, trying to read data with the shotnum or index keywords set as well as the add_controls keyword causes a "ValueError: Valid 'shotnum' not passed" error, even when the shotnum is valid. The desired behavior here is probably that a subset of the pos array corresponding to the requested shots should be returned?

In the future, it would be useful to have a read_pos( controls ) function that returns the position array associated with a control without loading any data.

**Comment by rocco8773** [comment]
Does the [`read_controls`](https://bapsflib.readthedocs.io/en/latest/src/bapsflib.lapd._hdf.file.html#bapsflib.lapd._hdf.file.File.read_controls) method do what you meant with a `read_pos` method?

**Comment by pheuer** [comment]
pos = f.read_controls(controls)['xyz'] does what I am looking for, thanks!

I was unable to reproduce this issue in a separate example file, so it's not an issue with bapsflib: you can close the issue.

**Comment by rocco8773** [comment]
Sounds good.  Let me know if the error ever comes back.
