### ISSUE TITLE
On the SmPD, the 'SIS 3301' digitizer labels the shot number field as 'Shot number' instead of 'Shot'

### ISSUE THREAD

**Issue by rocco8773** [BaPSF/bapsflib#28]
Traditionally, the `'SIS 3301'` digitizer header datasets label the shot number field as `'Shot'`.  At some point this field was re-labeled as `'Shot number'`.

This is evident in the HDF5 files generated by the SmPD, but I do not know when this change occurred or if it occurred while the `'SIS 3301'` was still being used on the LaPD.

**Comment by svincena** [comment]
I'm looking at an LaPD HDF5 file with SIS 3301 digitizer data from 2008,
and the label for the shot number is "Shot number"
