### ISSUE TITLE
Access motion list metadata associated with data

### ISSUE THREAD

**Issue by pheuer** [BaPSF/bapsflib#32]
Some metadata about the motion list associated with a dataset would be useful to have when processing the data. For example, dx/dy/dz, grid center coordinates, and especially Nx,Ny,Nz. Ideally these parameters would always be in the info dictionary, and would just be set to 0, 1, or NaN as appropriate if they do not exist in the HDF file. 

I realize figuring out which motion list goes with a particular probe is non-trivial. I suggest determining the motion list associated with a probe by looking at the "Motion list" column of the position data array for that probe, then searching for a matching motion list and associating them. This is kludgey, but not nearly as much as what I'm having to do to get around not having this information.

**Comment by rocco8773** [comment]
As you alluded to, determining which motion list is used can require some significant overhead.  Currently, when a motion dataset is recorded in the HDF5 file the associated motion list(s) are not saved in the metadata for the dataset, but in one of the columns of the dataset.  So, to determine which motion list(s) were used, the entire column has to be read into memory.  If this was automatically done during file mapping (i.e. file opening) then this could lead to a large execution time.

I'll open an issue to request a method a user could use to identify the used motion list(s) after the file is opened and mapped.

For now, there are three ways you can access the motion list data.  I'll use the `'6K Compumotor'` as an example, but this should work with any motion control type (i.e. `'NI_XZ'` and any future motion control device).

1. print out the the report of the `'6K Compumotor'`

    ```
    >>> from bapsflib import lapd
    >>> f = lapd.File('sample.hdf5')
    >>> f.overview.report_controls('6K Compumotor')
    ```

1. directly access the attributes dictionary of the motion list configuration group

    `f['Raw data + config/6K Compumotor/Motion list: <ml name>'].attrs` where `<ml name>` is the name of the motion list

1. access the motion list through the HDF5 file mapping classes

    ```
    >>> # list control configuration names
    >>> # for the 6K Compumotor this is the receptacle number
    >>> list(f.controls['6K Compumotor'].configs)
    [3]
    >>> f.controls['6K Computmotor'].configs[3]['motion lists']
    {'xy0-Nx55Ny35-dxy1cm': {'center': array([-5., -2.,  0.]),
      'created date': '10/28/2013 11:07:14 PM',
      'data motion count': 1925,
      'delta': array([1., 1., 0.]),
      'group name': 'Motion list: xy0-Nx55Ny35-dxy1cm',
      'group path': '/Raw data + config/6K Compumotor/Motion list: xy0-Nx55Ny35-dxy1cm',
      'motion count': 1960,
      'npoints': array([55, 35,  1])}}
    ```
