### ISSUE TITLE
Integrate pep8speaks

### ISSUE THREAD

**Issue by rocco8773** [BaPSF/bapsflib#37]
Integrate [pep8speaks](https://pep8speaks.com/) to automatically review Python code style

**Comment by physicistphil** [comment]
Make sure to set max line length to 100 :P

**Comment by AquaDragonTRS** [comment]
this would be useful, I dont know what the format of the line wrap is when writing new code. it looks like it wraps at 80 characters or something.

**Comment by rocco8773** [comment]
@AquaDragonTRS PEP8 is Python's style guide. A lot of IDEs will have these checks built in to show you as your coding.  [Line length is 79 characters](https://www.python.org/dev/peps/pep-0008/#maximum-line-length), and it suggest that you stick around 72 for comments/docstrings.

I agree. This is something I'd like integrated in the near future.
