### ISSUE TITLE
Incorrect clock rate at reduced sampling rates

### ISSUE THREAD

**Issue by pheuer** [BaPSF/bapsflib#45]
I loaded in a dataset that was recorded on the slow (100 MHz) DAQ at a reduced sampling rate of 12.5 MHz, but the clock rate returned by bapsflib was still 100 MHz.  A minimal example illustrating the problem is below. The data file used in the example can be found at data/BAPSF_Data/Laser_Shock/March2018/101-isatsweep_plane-p13-300G.hdf5

`from bapsflib import lapd as bapsf_lapd
import os

src = os.path.join("F:", "LAPD_Mar2018", "HDF","101-isatsweep_plane-p13-300G.hdf5")

with bapsf_lapd.File(src, silent=True)  as sf:
       src_digitizers = sf.digitizers
       digi = src_digitizers['SIS crate']
       daq_config = digi.active_configs[0]
        
       name, info = digi.construct_dataset_name(2, 4,  adc='SIS 3302',
                                                config_name = daq_config,
                                                return_info=True)
       clock_rate = info['clock rate']
       print(clock_rate)
        #Actual clockrate was 12.5 MHz, as recorded in the title of the config
       print(daq_config)`

**Comment by rocco8773** [comment]
The **clock rate** of the digitizer is different than the **sample rate**.  The `'SIS 3302'` always has an "internal" clock rate of 100 MHz but the sample rate differs if you are doing a sample averaging.  Can you check the [`'sample average (hardware)'`](https://bapsflib.readthedocs.io/en/latest/src/bapsflib._hdf.maps.digitizers.siscrate.html#bapsflib._hdf.maps.digitizers.siscrate.HDFMapDigiSISCrate.construct_dataset_name) and ensure the it is `8`.  The [`dt`](https://bapsflib.readthedocs.io/en/latest/src/bapsflib._hdf.utils.hdfreaddata.html#bapsflib._hdf.utils.hdfreaddata.HDFReadData.dt) attribute on the extracted data will give the the temporal step size for the sample rate, opposed to the clock rate.

**Comment by pheuer** [comment]
Thanks: that clarifies the issue. 'sample average (hardware)' does work, but I think the best solution is for me to just extract dt from the data instead of calculating it from the clock rate.
